[package]
name = "rs_pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
base64 = "0.22.1"
headless_chrome = {version = "1.0.17",features = ["fetch"]}
serde = "1.0.219"
tokio = {version = "1.45.1",features = ["full"]}

